# Generated by Django 4.0.1 on 2022-12-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
    ]
