# Generated by Django 4.0.1 on 2022-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='payment_mode'),
        ),
    ]
