# Generated by Django 4.0.1 on 2022-12-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='size',
        ),
        migrations.AddField(
            model_name='transaction',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='variant'),
        ),
    ]
