# Generated by Django 4.0.1 on 2023-01-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_transaction_size_transaction_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tracking_id'),
        ),
    ]
