# Generated by Django 4.0.1 on 2023-01-26 09:08

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=product.models.nameFile, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=product.models.nameFile, verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=product.models.nameFile, verbose_name='image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=product.models.nameFile, verbose_name='image4'),
        ),
    ]
