# Generated by Django 4.0.1 on 2022-12-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
    ]
