# Generated by Django 4.0.1 on 2023-01-10 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='fullname')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='message')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='product_name')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='mobile_number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
