# Generated by Django 4.0.1 on 2023-01-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='quote',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contact_number'),
        ),
    ]
