# Generated by Django 4.0.1 on 2023-01-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_remove_quote_mobile_number_quote_contact_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Recom',
        ),
    ]
