# Generated by Django 4.0.1 on 2023-01-26 09:34

from django.db import migrations, models
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_quote_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=quote.models.nameFile, verbose_name='image'),
        ),
    ]
