# Generated by Django 4.0.1 on 2022-12-20 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0.0, verbose_name='product_id')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='user_id')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='size')),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_from')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
