# Generated by Django 4.0.1 on 2022-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='product_name'),
        ),
    ]
