# Generated by Django 4.0.1 on 2022-12-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='variant'),
        ),
    ]
