# Generated by Django 4.0.1 on 2022-12-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_date_from_cart_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=0.0, verbose_name='product_id'),
        ),
    ]
