# Generated by Django 4.0.1 on 2022-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variant',
        ),
        migrations.AddField(
            model_name='cart',
            name='sizeColor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sizeColor'),
        ),
    ]
