# Generated by Django 4.0.1 on 2022-12-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_cart_variant_cart_sizecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sizeColor',
        ),
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='variant'),
        ),
    ]
